# ------------------------------------------------------------
# Copyright 2021 The Dapr Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------

name: Publishing test coverage reports of components

on:
  repository_dispatch:
    types: [certification-test]
  workflow_dispatch:
  # schedule:
  #   - cron: '25 */8 * * *'
  push:
    branches:
      - aggregate_coverage
  # pull_request:
  #   branches:
  #     # TODO: REMOVE "master" BEFORE MERGING
  #     - 'master'
  #     - 'release-*'

jobs:
  gocov:
      name: Download and merge gocov reports
      runs-on: ubuntu-latest
      env:
        GOVER: "1.20"
      steps:
        - name: Set up Go ${{ env.GOVER }}
          if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
          uses: actions/setup-go@v3
          with:
            go-version: ${{ env.GOVER }}
        
        - name: Setup go dependencies
          run: |
            go install github.com/axw/gocov/gocov@v1.1.0
            go install gotest.tools/gotestsum@latest
            go install github.com/wadey/gocovmerge@latest
        
        - name: Download workflow artifact
          if: always()
          uses: dawidd6/action-download-artifact@v2.24.3
          with:
            workflow: certification.yml
            workflow_conclusion: "success"
            branch: aggregate_coverage
            if_no_artifact_found: warn
            name: cert_code_cov
            path: tmp/cert_code_cov

        